#!/bin/bash -xe

. ./hooks/env

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%d"` --build-arg "SOURCE_REF=$GIT_SHA1" --build-arg "DOCKERFILE_PATH=$DOCKERFILE_PATH" --build-arg "SOURCE_TYPE=$SOURCE_TYPE" -t $IMAGE_NAME $DOCKERFILE_PATH
