#!/bin/bash -e

. ./hooks/env

function retry {
  local retry_max=$1
  shift

  local count=$retry_max
  while [ $count -gt 0 ]; do
    "$@" && break
    count=$(($count - 1))
    sleep 1
  done

  [ $count -eq 0 ] && {
    echo "Retry failed [$retry_max]: $@" >&2
    return 1
  }
  return 0
}

function finish {
  RESULT=$?
  [ -n "$CID1" ] && docker logs ${CID1}
  [ -n "$CID1" ] && docker rm -f ${CID1}
  [ $RESULT = 0 ] && echo "PASS" || echo "FAIL"
}
trap finish EXIT

function container_healthy {
  docker inspect $1 | grep -q \"Status\".*\"healthy\"
}

# setup
CID1=$(docker run -d $IMAGE_NAME)

# tests
retry 125 container_healthy ${CID1}

retry 5 docker run --rm --network container:${CID1} appropriate/curl -s -o /dev/null http://localhost:80/colplot/
